### ISSUE TITLE
发起请求client空指针

### ISSUE THREAD

**Issue by q1055145251** [xiao-ren-wu/restgo#1]
func init() {
	client = &http.Client{
		Timeout: time.Duration(15) * time.Second,
		Transport: &http.Transport{
			MaxIdleConnsPerHost:   512,
			MaxConnsPerHost:       512,
			IdleConnTimeout:       90 * time.Second,
			TLSHandshakeTimeout:   10 * time.Second,
			ExpectContinueTimeout: 1 * time.Second,
		},
	}
}

type defaultRestGo struct {
	client *http.Client
	trace  *httptrace.ClientTrace
}

var defaultRestGoInstance RestGo = NewDefaultRestGo(client, nil)

**Comment by q1055145251** [comment]
应该是这个位置的启动顺序问题导致的，麻烦修复一下

**Comment by xiao-ren-wu** [comment]
解决了，忘记关了
